//
export const shiftColumn = [
  {
    key: 'checkbox',
    label: '',
    maxWidth: 40,
    width: 40,
    type: 'checkbox',
    class: 'col-checkbox',
  },
  {
    key: 'shiftCode',
    label: 'Mã ca',
    width: 122,
    filterable: true,
  },
  {
    key: 'shiftName',
    label: 'Tên ca',
    width: 250,
    filterable: true,
  },
  { key: 'beginShiftTime', label: 'Giờ vào ca', width: 130, type: 'time' },
  { key: 'endShiftTime', label: 'Giờ hết ca', width: 130, type: 'time' },
  { key: 'beginBreakTime', label: 'Bắt đầu nghỉ giữa ca', width: 200, type: 'time' },
  { key: 'endBreakTime', label: 'Kết thúc nghỉ giữa ca', width: 200, type: 'time' },
  {
    key: 'workingTime',
    label: 'Thời gian làm việc (giờ)',
    width: 150,
    type: 'number',
    class: 'text-align-right',
    filterable: true,
  },
  {
    key: 'breakingTime',
    label: 'Thời gian nghỉ giữa ca (giờ)',
    width: 150,
    type: 'number',
    class: 'text-align-right',
    filterable: true,
  },
  { key: 'inactive', label: 'Trạng thái', width: 200, type: 'custom', filterable: true },
  { key: 'createdBy', label: 'Người tạo', width: 120, filterable: true },
  { key: 'createdDate', label: 'Ngày tạo', width: 150, type: 'date', filterable: true },
  { key: 'modifiedBy', label: 'Người sửa', width: 120, filterable: true },
  { key: 'modifiedDate', label: 'Ngày sửa', width: 150, type: 'date', filterable: true },
  {
    key: 'action',
    label: '',
    width: 100,
    maxWidth: 100,
    type: 'custom',
    class: 'col-action',
  },
]
